### ISSUE TITLE
The problem with saving language files for tests before running the tests

### ISSUE THREAD

**Issue by mkaze** [koaning/whatlies#107]
The following warning from automated tests is what I was mentioning about the problem with saving model files for tests beforehand:

![spacy-stale](https://user-images.githubusercontent.com/8656825/89306260-db360880-d684-11ea-9efd-555803bc4f81.png)

Although, it's just a warning and hopefully newer versions of any language library (not just spaCy) is backwards-compatible (though, I don't think spacy is backwards-compatible always). 

And also since the saving format may change between different versions of libraries, or is not deterministic for all the machines/envs, you would get these in your git status:

![git-status](https://user-images.githubusercontent.com/8656825/89306823-9f4f7300-d685-11ea-87e6-4c96e646a5f4.png)

These are not serious issues, yet; but I just wanted to bring them up so that we have them on our radar.

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
So spaCy is going to release version 3.0 at some point in the not super distant future. Once that is out I'll gladly pick this up. There's bound to be quite a few versioning issues we can adress.

**Comment by koaning** [comment]
We could add some extra files to gitignore. But with the advent of github caching we might be able to run tests on downloaded language models more easily.

**Comment by koaning** [comment]
Since the repository moved to my personal account I'm moving this project into maintenance mode. This issue, while interesting, likely won't get the attention it needs in the future.
