### ISSUE TITLE
The return value of plot methods

### ISSUE THREAD

**Issue by mkaze** [koaning/whatlies#140]
*This is partly relevant to #127.*

 Currently, the following methods return a reference to the plot objects:
- `plot_interactive_matrix`
- `plot_interactive`
- `plot_movement`

However, the following methods either return `None` or `self`:
- `plot_pixels`
- `plot_correlation`
- `plot_graph_layout`
- `plot` from `EmbeddingSet`
- `plot` from `Embedding`

Isn't it better that the methods in the latter group also return a reference to the plot object? This makes them all have similar interface, as well as gives the user the ability to tune the plot object further if desired (although, the methods in the second group use `matplotlib` and therefore the plots could be customized with `plt.the_relevant_function(...)` as well).

**Comment by koaning** [comment]
I certainly agree that we could apply some more consistency there. Sofar I've been able to use hacks like this in the notebook to suit my needs: 

```
plt.figure(figsize=(8,8))
emb.plot_pixels()
```

If we could maintain the ability to allow for these hacks in the notebook that'd be neat but I agree that proper consistency is more important.

**Comment by koaning** [comment]
One caveat: the `plot` method from the `Embedding` is really only meant for demo purposes. I am also considering deprecating `plot_correlation` in favor of `plot_distance` and `plot_similarity`.

**Comment by mkaze** [comment]
> the plot method from the Embedding is really only meant for demo purposes

If it's there and also there is no plan to deprecate it, then it should work properly, right? I am asking this because I have found one problem with it in a rather niche case: it does not project the 2D-embeddings if `x_axis` and/or `y_axis` are `Embedding` instances; rather, it just draw the embedding itself. Though, it will be probably fixed in the PR for #125.

**Comment by mkaze** [comment]
Unfortunately, this is a breaking change especially that chained `plot` calls have been used [in the tutorials](https://rasahq.github.io/whatlies/tutorial/embeddings/#plotting-high-dimensions). @koaning I don't think you be in favor of it in that case.

**Comment by koaning** [comment]
If I'm honest, I think the library doesn't have *that* many users yet. Here's the views for the relevant documentation page; 

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/1019791/90272873-5ace8f00-de5e-11ea-90a4-dc74ab8fba9c.png">

In 60 days maybe 100 people looked at it? That's maybe two people a day? Assuming they don't 100% fully read and instead just glance I'd say it may be not be the worst of worst things to happen. But we shouldn't have breaking changes often. 

As long as we update the docs immediately I think I can live with it.

**Comment by koaning** [comment]
Another way to think about this; I think that in this phase I can say that there are more future users of this tool than past users of this tool. That means that we could allow ourselves a little bit more wiggle room towards "yeah we changed how something works, but we can definitely defend that the new change makes life so much better". Especially when the changes are relatively minor. 

After we might publish a paper on this tool and after I might speak about this tool at PyData and we see more activity ... then this attitude won't be valid anymore. Now though, I'd say we can still be liberal in our changes. Big changes, like the deprecation of a method, should first receive a deprecation warning though.

**Comment by koaning** [comment]
I'm closing issues because ever since the project moved to my personal account it's been more into maintenance mode than a "active work" mode.
