### ISSUE TITLE
Allow for embset_deb = embset | embset_gender_axes

### ISSUE THREAD

**Issue by koaning** [koaning/whatlies#159]
If I want to apply the classical debiasing technique I can now run:

```python
embset_deb = embset | (embset['man'] - embset['woman'])
```

This is neat, but it unfortunately only works on a single embedding. I cannot do this: 

```python
gender_axes = EmbeddingSet(
  embset['man'] - embset['woman'],
  embset['king'] - embset['queen'],
  embset['doctor'] - embset['nurse']
)

embset_deb = embset | gender_axes
```

There are use-cases for projecting away from a plane as opposed to a single axis. Right now the only method we can offer for this debasing use-case is; 

```python
gender_axis = EmbeddingSet(
  embset['man'] - embset['woman'],
  embset['king'] - embset['queen'],
  embset['doctor'] - embset['nurse']
).average()

embset_deb = embset | gender_axis
```

I think it would be nice to also allow the projection of planes. I don't think we can do this for the other operators though. 

Also, I am now of the opinion that this, as a debiasing technique, is faulty. I would still like to feature it in this library though because it is easy to demonstrate why it is so.

**Comment by mkaze** [comment]
So basically by `a | b` where both `a` and `b` are `EmbeddingSet` instances you want each embedding in `a` to be orthogonalized to all embeddings in `b`, right? If so, I think it could be done with Gram Schmidt approach.

**Comment by koaning** [comment]
@mkaze precisely! This is what Gram-Schmidt should do. I don't know if numpy/scipy implements this.

**Comment by mkaze** [comment]
@koaning I am not completely sure, but maybe QR decomposition might help which have been implemented in numpy ([here](https://numpy.org/doc/stable/reference/generated/numpy.linalg.qr.html)).

**Comment by koaning** [comment]
I've written my own implementation of (a variant of) Gram-Schmidt before for [another project](https://scikit-lego.readthedocs.io/en/latest/fairness.html#Information-Filter). I recall trying the QR route but having a lot of trouble getting it to align with the axes that I was interested in. I'll give it another look, but a custom function could be fine as well here.

**Comment by mkaze** [comment]
@koaning All right! Though, I have read before that there might be some numerical issues which needs to be taken care of if you want to implement GS in the straightforward way

**Comment by koaning** [comment]
Since the repository moved to my personal account I'm moving this project into maintenance mode. This issue, while interesting, likely won't get the attention it needs in the future.
