### ISSUE TITLE
Should "transform" method make copies of embeddings in transformers?

### ISSUE THREAD

**Issue by mkaze** [koaning/whatlies#163]
Currently, there is a requirement that the "property" added to embeddings in a `EmbeddingSet` instance should be preserved when a transformer is applied on them. So far, so good. However, do we want to preserve the reference (if possible) or always make a copy? To make it clear, in `AddRandom` just [a **shallow copy** is made][1] (hence `embset['foo'] is embset.transform(AddRandom())['foo'] == True`; this is also applicable to the properties of embeddings); however, in all the other transformers a **deep copy** is made and then modified if necessary.

Does this even matter?

[1]: https://github.com/RasaHQ/whatlies/blob/2b154fd70bbb78add9768a983ffb5be1a7bdc440/whatlies/transformers/addrandom.py#L50

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @melindaloubser1 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
I usually prefer to always make a copy because it is slightly easier to reason about. Things become immutable so less unintended side effects. I can't recall a very conscious on my part here besides this immutability point.

**Comment by mkaze** [comment]
> @mkaze What's your main concern here, performance or code-readability?

One concern is that the `Embedding` object is mutable and therefore making a shallow copy would keep the references. For example:

```python
foo = Embedding(...)
bar = Embedding(...)
embset = EmbeddingSet(foo, bar)

assert embset['foo'] is embset.transform(AddRandom())['foo']
```
So any change in `embset['foo']` would be reflected in `embset.transform(AddRandom())['foo']` as well and vice versa.

Another concern, which is more general than the previous one, is the question: in which one of the operations performed on `Embedding` as well as `EmbeddingSet` objects the return value should be a deep copy instead of a reference? For example, `EmbeddingSet.merge` returns reference instead of copy:

```python
from whatlies import Embedding, EmbeddingSet                                                             

foo = Embedding('foo', [1,2])                                                                            
bar = Embedding('bar', [3,4])                                                                            
buz = Embedding('buz', [5,6])                                                                            
taz = Embedding('taz', [7,8])                                                                            

embset1 = EmbeddingSet(foo, bar)                                                                         
embset2 = EmbeddingSet(buz, taz)                                                                         

m = embset1.merge(embset2)                                                                               
assert m['foo'] is foo
                                                                                          
m['foo'].vector                                                                                         
# array([1, 2])
foo.vector                                                                                              
# array([1, 2])

foo.vector[1] = 10                                                                                      
foo.vector                                                                                              
# array([ 1, 10])
m['foo'].vector                                                                                         
# array([ 1, 10])
```

**Comment by koaning** [comment]
I think in general, we should do deep copy. There's a performance hit when you do this, but the benefit is that there's way less unexpected moments. Pretty much why pandas is now completely dropping the `inplace=True` option. 

I'm open to discussing this though. I've never experienced the performance hit noticeably nor have I ever been bitten by a "mutable surprise" (that I'm aware of).

**Comment by mkaze** [comment]
@koaning Sure, I am also in favor of deep copy here (unless we change some of the assumptions in the entire library).
(just a quick note about pandas point you mentioned: as I see and understand it, that's partly true but not the whole story! The promise of inplace operations is to save some memory, however this is not happening properly in pandas for the most part).

**Comment by koaning** [comment]
I'm closing issues because ever since the project moved to my personal account it's been more into maintenance mode than a "active work" mode.
