### ISSUE TITLE
Implementation of Curated Word Lists

### ISSUE THREAD

**Issue by koaning** [koaning/whatlies#170]
I think we've reached the point where curated word lists might make sense. I'm wondering what the most convenient API might be. 

I'm wondering if we could have an api like:

```python
from whatlies.wordlist.en import gendered, top_n, stopwords

words = gendered(male=True, female=False, cursewords=False)
words = top_n(n=10000)
```

It feels like we can save some csv files in our project and that we can have functions deal with the logic of subsetting. @mkaze any thoughts on this? I think we'll need to add a language submodule (`en`) such that if users ever want to submit words for different languages that we have a place to put them. Once concern that I have is that these wordlists might become big and that our package might get bigger as a result too.

**Comment by mkaze** [comment]
> Once concern that I have is that these wordlists might become big and that our package might get bigger as a result too.

They should not be necessarily part of the package. Instead, we can put them outside of the package and provide them on-demand by downloading them (e.g. this is [how Keras datasets are handled](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/keras/datasets) or [like NLTK](https://www.nltk.org/data.html)). We can even go one step further and create another layer of separation for managing them by putting them entirely in a separate repository on Github (named as `wlwl` for "whatlies word lists" :smile: ) so that all the issues and PR as well as downloads would be done seperately on and from Github.

**Comment by koaning** [comment]
@mkaze that's a valid point. I can imagine that proper word-lists at some point deserve their own package considering. Not just due to the reviewing aspect but also due to the fact that it is a more general package. 

I'll need to check in with some folks here at Rasa how we might want to host it. The advent of maintaining a word-list repo  with multiple languages might make some people nervous so it is best to check. Due to the general nature of it we might also just call it `wordlist`.

**Comment by koaning** [comment]
Come to think of it. Maintaining a word-list repo is actually really hard. If we have a contributor, say, from Finland. I have no proper way to check if the contributor is contributing curse-words or gendered words. Especially if we want to have a word-list that folks can rely on, we'd need a proper way to prevent this.

**Comment by mkaze** [comment]
Well, that's where the trust comes into play.
Although, there might be some ways of checking to some extent, e.g. using Google translate. But at the end, it's a trust issue. At the same time, the good thing about being open-source is that it the issues like these would be spotted and fixed as soon as it raises concerns. And a disclaimer note could be added to discard any such responsibility.

**Comment by koaning** [comment]
I fear it's a bit naive to suggest that we can "discard any such responsibility". It's certainly a must to mention that the lists are never going to be perfect. But if people start trusting them, you do carry some responsibility as a maintainer even if you add a disclaimer. 

I'll ask around. Maybe there's some folks in academia who want to collaborate here. Another option is to keep the word-lists limited to English initially.

**Comment by mkaze** [comment]
I didn't mean all kinds of responsibility, that's why I used the word "such" :wink:; rather I was mostly referring to something along the lines of:

> Disclaimer: we do our best to provide clean and unbiased datasets so that all people could use for various purposes; however, since this is by nature a community-driven effort in which people with different language skills can collaborate and provide data, and there might be languages which the maintainers may not have enough knowledge about, it would be very hard to guarantee that our data is completely unbiased and clean of any errors. So you should consider this point if you use the datasets in this repository in your work, research or presentation. Of course, we do welcome and appreciate reporting of such errors so that we could fix them as soon as possible. Thank you for your understanding!

**Comment by koaning** [comment]
Fair enough :) Good disclaimer by the way.

**Comment by koaning** [comment]
There's a wordlist project here: https://github.com/imsky/wordlists

It's out of scope for this project.
