### ISSUE TITLE
Allow for sorting on EmbeddingSet

### ISSUE THREAD

**Issue by koaning** [koaning/whatlies#179]
Plots like `embset.plot_distance` can show clusters. It is nice to be able to sort these beforehand. It might make sense to allow for methods like; 

## Sorting using lambda 

```
embset.sort(lambda e: e.group)
```

## Sorting using property

It can also be nice to just directly be able to sort on a property that is attached on the embeddings. 

```
embset.sort_property("group")
```

**Comment by Ayushsunny** [comment]
Sir @koaning What exactly I need to to do in this issue to get fixed ?

**Comment by koaning** [comment]
I'm closing issues because ever since the project moved to my personal account it's been more into maintenance mode than a "active work" mode.
