### ISSUE TITLE
Visualization API and its connection to backends

### ISSUE THREAD

**Issue by mkaze** [koaning/whatlies#202]
A more or less recurring topic in the issues (and probably in our minds) is the discussion of visualization API and its connection to different visualization backends which are already supported or will be supported in the future. Hence, I thought it's worth having a dedicated issue for it in order to discuss it clearly and coherently in one place.

**Comment by mkaze** [comment]
There is a relevant question that is lingering in my mind for a while: is there any way to have a unified visualization **public** API instead of having a separate method for each backend? In other words, instead of having `plot` and `plot_interactive` (or `plot_altair` vs. `plot_bokeh` vs. `plot_matplotlib` as suggested in the above comment), could we have a single `plot` method and handle backends differently under-the-hood? (of course, one may argue that there is another question which should be answered first: why does having a unified API matter? or how does it help?)

**Suggestion:** I think it could be implemented in one of the following ways or even a hybrid of them:
- Set backend globally. For example:
    ```python
    import whatlies

    # matplotlib will be used by default
    embset.plot(....)
    embset.plot_distance(...)    

    whatlies.set_vis_backend('altair')
    # all the following plots will be plotted by altair (if possible)
    embset.plot(...)
    embset.plot_distance(...) 
    ```

- Pass the desired visualization backend as an argument to the unified API methods. For example:
    ```python
    embset.plot(...)  # matlplotlib will be used by default
    embset.plot(..., backend="altair")    # altair will be used for this plot
    ```
As I mentioned above either one of these solutions, or preferably both of them could be implemented. I am not sure and convinced about the usefulness of these solutions, though. They may not save the user from writing, but at least it makes the API simple and unified. @koaning Since I read your comment [here](https://github.com/RasaHQ/whatlies/issues/200#issuecomment-688293664), I thought it would be useful to free my mind and write down this idea here :smile:

**Comment by koaning** [comment]
I really like this proposal. It is breaking, but since we can keep `plot_interactive` around for a deprecation period I only see upsides. 

I would be interested in a hybrid solution of your proposal. I can imagine that certain charts work in inter-active mode while other charts are just better looking with matplotlib. For example; plot_distance is possible in altair, but perhaps not better looking. I can also imagine, with the advent of 3d plotting, that certain backends may not allow for everything. Matplotlib might allow for a 3d plot but Altair certainly does not.  Matplotlib allows you to draw arrows, I'm not 100% sure of Altair here.

**Comment by mkaze** [comment]
> I really like this proposal. It is breaking, but since we can keep plot_interactive around for a deprecation period I only see upsides.

Glad to hear that you also have a favorable opinion about this. Actually, when I was thinking about this I was a bit hesitant and thought maybe it's not a neat/sane solution (especially the global setting). But I just find out right now that [Pandas also uses almost exactly the same approach](https://pandas.pydata.org/docs/user_guide/visualization.html#plotting-backends) which I was not aware of at all until now. Of course, the fact that another (popular) library is using the same approach does not justify that we should necessarily follow the same approach; but it was uplifting for me to find out that, since it shows me that I have not gone totally mad yet :smile: :smile:

**Comment by koaning** [comment]
The devil will be in the details here, my spidey-sense is tingling too, there's probably going to be loads of details, but I agree that a unified API should be our "north star". I imagine that we're probably going to really start writing code for this feature after we've done at least one iteration on the unified language/transformation backend. Partially because lang/tfm is a more defined task but also because there are many details to get right here api-wise. 

For starters, are you still in favor of adding bokeh?

**Comment by mkaze** [comment]
It seems I have missed the three questions you asked as they have been added later.

> 1. Would we be interested in having both `.plot()` and `.plot_interactive()`? Technically, `Altair` can make non-interactive charts. For a unified API to work swell, we wouldn't want to have many keyword arguments in the `.plot()` method that only apply to a specific backend. We could add `.plot(interactive=True)` for example, but this would be meaningless for matplotlib.

I am not sure about this. Adding an argument might be a good solution, as I think about it like grouping the similar charts by their "kind" rather than visual details/options, and assign a single method to each group. 

> 2. Do we have an overview of all the backends that we want to support? What are the main features not in `Altair` and `matplotlib`  that we do want to have in this API?

This is a good question as it's also highly related to the question of "why do we want to support additional backends in the first place?". Two points come to my mind regarding this:

- The currently supported backends might not support a specific feature/plot which we (or the community of users) find very useful to have. Therefore, we might decide to add support for an additional backend. Of course, there is a costs-benefit tradeoff here: only one single missing feature/plot might not justify adding the support for a new backend and including it in all the plot methods.

- There is the issue of familiarity or taste or favoritism regarding a specific visualization library from a **rather large** group of users (we already saw one such feedback in #86). Beyond the discussion and merit of preference, the familiarity enables the user to further configure and customize the charts using their preferred library for their specific use case (e.g. presentation, research paper, etc.), instead of putting time and effort to learn a new visualization backend. 

> 3. Will we have also have `.plot_3d()`?

My answer is yes, but regarding the specifics I think we already have some ongoing discussion in #200.

> For starters, are you still in favor of adding bokeh?

Well in general I would give the answer I just gave for question (2). However, I like bokeh because of its widgets and its visually appealing plots. But I should warn you that I am not a good candidate in this domain at all, because 1) I rarely use visualizations in my works due to the nature of it, 2) I haven't worked with an extensive set of visualization libraries to be able to compare their pros and cons clearly. I think you have much more experience there; so take my views as something that comes from an inexperienced person in the visualization domain (and please feel free to disagree with my views firmly to signal me that they don't make sense and I should stop going further :smile: :smile:).

**Comment by koaning** [comment]
I've drawn a small overview of different plotting backends and the general charts we've hosted here. 

![image](https://user-images.githubusercontent.com/1019791/92607466-75a4ef80-f2b4-11ea-97b8-3b34971de066.png)

It seems that we can support most backends no problem. The main caveat seems to be the `plot_3d` method. I'm also have a gut feeling that bokeh has more users than plotly. But I could be mistaken.

**Comment by koaning** [comment]
I'm closing issues because ever since the project moved to my personal account it's been more into maintenance mode than a "active work" mode.
