### ISSUE TITLE
Transformer API design and implementation

### ISSUE THREAD

**Issue by mkaze** [koaning/whatlies#204]
It's good to have a dedicated place for discussing ideas about the transformer API design and also the potential improvement/refactoring options in its implementation. Specifically, we are interested to find out what the drawbacks of the current API design (and/or implementation) is, and how it could be further improved.

**Note that if we an issue/idea is big enough to merit having a dedicated issue or we decide to implement a particular idea/feature, feel free to create a new specific issue for that to be able to track them easily.**

**Comment by sara-tagger** [comment]
Thanks for the issue, @b-quachtran will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
I'm currently working on a PR to help this disucssion. I might have found a nice balance API wise and I it might help the discussion to have a code example to point to.

**Comment by koaning** [comment]
Good to mention: not every transformer will fit this API though. The `Noise` transformer seems like the exception. I've ignored `AddRandom` because I'm assuming that we're deprecating it (do we agree?).

**Comment by koaning** [comment]
I'm closing issues because ever since the project moved to my personal account it's been more into maintenance mode than a "active work" mode.
