### ISSUE TITLE
Handling custom attributes/properties

### ISSUE THREAD

**Issue by mkaze** [koaning/whatlies#219]
There is this suggestion by @koaning ([here](https://github.com/RasaHQ/whatlies/pull/214#issue-485093333)) to not assign custom properties directly on the `Embedding` object itself. He suggests using a separate attribute, say `data`, which would hold all the custom properties/attributes. For example, the API would look like this:

```python
embset = EmbeddingSet(foo, bar)

embset = embset.assign(x=lambda e: e.vector[0], y=lambda e: e.vector[1])

embset['foo'].x  # raises error after this change (maybe?!)
embset['foo'].data.x    # equals: `embset['foo'].vector[0]
# or using brackets:
embset['foo'].data['x'] # equals: `embset['foo'].vector[0] 

embset['bar'].y  # raises error after this change (maybe?!)
embset['bar'].data.y    # equals: `embset['bar'].vector[1]
# or using brackets:
embset['bar'].data['y'] # equals: `embset['bar'].vector[1]

```
This looks good to me as well. However, if we decide to keep the API as currently is, i.e. let `embset['foo'].x` work as before, we can also resolve attribute accesses using `__getattr__` method. For example, in `Embedding` class implementation we would have:

```python
def __getattr__(self, name):
    # It depends on how `data` attribute has been implemented
    return getattr(self.data, name)
    # or:
    return self.data[name]
```
Of course with this last addition, the custom properties with the same name as built-in attributes, like `vector` or `name`, can only be accessed using `data` attribute (I think this is also similar to how some libraries like Pandas handle the same situation).

**Comment by koaning** [comment]
Another option might be that we attach one more property to the `Embedding` called `data` to deal with custom properties. This can be a dictionary that the user is allowed to edit. We could declare that that should be the "only" place where the user is allowed to fiddle and by keeping it as a dictionary we might be able to simplify a lot of things.

```python
embset = EmbeddingSet(foo, bar)
embset = embset.assign(x=lambda e: e.vector[0], y=lambda e: e.vector[1])
assert embset["foo"].data == {"x": 0.1231, "y": -2.4112}
```

**Comment by koaning** [comment]
Related idea. Whats the over-arching goal of these properties? Is it just for plotting color? Maybe we'd like to generate dataframes. I was in a call today with researchers from Sussex and they mentioned that they're interested in, not just plots, also statistics. Say you're investigating if the vector norm has a relationship with "weather or not it is a stop-word" then something like this would be nice; 

```python
(embset
  .assign(norm_dist = lambda e: e.norm)
  .assign(stopword = lambde e: e.name in stopword_list)
  .to_dataframe())
```

The dataframe could contain all the properties that have been added. Potentially we can add a flag to also add the vectors in the users wants it.

**Comment by mkaze** [comment]
Yeah, I agree that the properties might have other use cases as well. That depends on the user and their creativity. We have simplified the user's life by providing a way to attach custom data to the embedding objects, instead of forcing them to store the custom data in a separate data structure. Obviously, as a result, this might open up some easier way of handling things (e.g. using the attribute value as color in plots). 

> The dataframe could contain all the properties that have been added. Potentially we can add a flag to also add the vectors in the users wants it.

Is [this](https://github.com/RasaHQ/whatlies/issues/156) what you are referring to?

**Comment by koaning** [comment]
I'm closing issues because ever since the project moved to my personal account it's been more into maintenance mode than a "active work" mode.
