### ISSUE TITLE
spacy language backend: sentence vs. token embeddings

### ISSUE THREAD

**Issue by mkaze** [koaning/whatlies#92]
*This is not a bug; rather it is more of a conceptual issue and a question to think about which may possibly improve the design and API of this library.*

The embeddings given by a spaCy model for a sentence is just the average of the token embeddings. For the `spacy-transformers`, this is the sum of token embeddings. So the question is: with spacy models, when we feed them a query string, are we more interested to get the sentence embedding or the embeddings of the tokens in that sentence (i.e. as an `EmbeddingSet` object)? spaCy provides both (i.e. `doc.vector` and `doc[i].vector`); however, here personally I prefer the latter because with spacy models I can get the sentence embedding from the token embeddings but not vice versa (besides the fact that simply averaging or summing the token embeddings of a sentence usually does not give a good representation of that sentence). Further, one of the interesting aspects of spaCy models is that they run a pipeline of modules on the query which starts from tokenization (and many use it for this one); so why not use it?

**Suggestion**: If modifying the current behavior of `__getitem__` is a no-no, we can instead add a new method called `embed` which takes a string as well as a boolean flag as input arguments, i.e. `embed(self, query, tokens=True)`. In the default case, i.e. `tokens=True`, it would first tokenize the query and then provide the token embeddings. If `tokens=False`, the result would be the same as `__getitem__`. Note that this method is not specific to `SpacyLanguage` backend and it could be used for any language backend that provides both of token and sentence embeddings (e.g. fasttext, hugginface). And further, unlike `__getitem__`, this method could take additional arguments which may add the support for backend-specific features. 

@koaning What's your opinion on this?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rgstephens will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
This will become a more important theme as we add more BERT-like models but to check, are you aware of this syntax? 

Example; 

```
[bank] of the river
```

The idea is that we want to have the embedding of `bank` in the context of `bank of the river`. You should be able to assume that; 

```python
lang['[bank] of the river'].vector != lang['money on the [bank]']
```

This is what the current API allows and this is what is documented [here](https://rasahq.github.io/whatlies/tutorial/languages/#bert-style). This might allow for part of your use-case. 

That said, I'm open to the idea of adding `.embed(self, query, tokens=True)` to the API. We should think about what it should return though; an embeddingset? A list of (string, vector)-pairs? 

Related: I'll need to give the API a good ponder. I want to implement huggingface/tfhub first but once I get an overview of what features I require of the language backends there'll be an opportunity to make an abstract base class so we can refactor a lot of things.

**Comment by mkaze** [comment]
> We should think about what it should return though; an embeddingset? A list of (string, vector)-pairs?

If you ask me, I would definitely say an `EmbeddingSet` instance when `tokens=True`, and an `Embedding` instance when `tokens=False`. Why do you think a list of (string, vector)-pairs might be more suited instead?

Ah, finally: adding a parent class for language backend classes and refactoring some of their methods is something which I have had in my mind for a while. I am glad to hear that you have this in mind as well. To also note here, I think the test coverage is also not enough and some restructuring is needed there as well.

By the way, are you currently working on huggingface and tf-hub integrations? :open_mouth: I am asking this so that we don't end up having duplicate implementations of these! :smile:

**Comment by koaning** [comment]
I've got a PR with ConveRT which is the first tf-hub integration. 

Dependency wise, it seems to be a small nightmare. You need `tensorflow-text` as well as `tensorflow-hub` and these dependencies make/break with certain `tensorflow` versions. It seems like we need to hard-pin those version numbers. 

I'd prefer doing the refactor until *after* I've played with a tfhub/huggingface so that I understand what we can abstract away and what we can't. For example ... Bert style models often don't offer a vocabulary so that means that `score_similar` may not work.

**Comment by mkaze** [comment]
> It seems like we need to hard-pin those version numbers.

If we agree on supporting only TF 2.x, then I think we don't need a strict version pinning. Just using `tensorflow>=2.0`, `tensorflow-text>=2.0` and `tensorflow-hub>=0.5.0` works if I am not mistaken.

> I'd prefer doing the refactor until after I've played with a tfhub/huggingface so that I understand what we can abstract away and what we can't. 

Sure, that's a good point.

**Comment by koaning** [comment]
I fear dependency stuff is more tricky. Let's keep the dependency conversation on this thread: https://github.com/RasaHQ/whatlies/issues/88#issuecomment-663558913

**Comment by mkaze** [comment]
For the sake of completeness, instead of `embed`, two other alternative options came to my mind last week:

- Adding a `set_config(emb_type='tokens', **other_potential_config_values)` method to a language class so that its behavior could be configured/modified (e.g. should the `__getitem__` return sentence or token embeddings; or in Hugging Face transformers should the embedding tokens be summed together or averaged, or which layer should be used for producing embeddings, etc.).

- Adding a `__call__` method which could do all the things `__getitem__` method could do, and also it could get additional arguments to customize produced embeddings. This is especially intuitive for TF or Hugging Face models which essentially run a computation graph to obtain the embeddings (unlike look-up methods such as word2vec) and this signature is native to them.

**Comment by koaning** [comment]
Suppose we go for the `config` option. 

What might be the output of this? 

```python
lang["this is a sentence"]
```

And what might be the output of this? 

```python
lang[["word", "this is a sentence"]]
```

I'm currently a little bit more concerned with the output.

**Comment by mkaze** [comment]
My initial thought:

`lang["this is a sentence"]` returns:
- an `Embedding` if sentence embedding is desired
- an `EmbeddingSet` if token embeddings are desired

`lang[["word", "this is a sentence"]]` returns:
- a `EmbeddingSet` if sentence embedding is desired
- a list of `EmbeddingSet` if token embeddings are desired

**Comment by koaning** [comment]
I'm still open to the feature but I fear for the cognitive load on the user. If you've understood that `lang[words]` will retreive an `EmbeddingSet` then I can imagine that it is very confusing to learn that this is not always the case. Probably better to just make an explicit method for it. 

One thing to also consider. Suppose we have a sentence like; 

`i like food`

then I might argue that we have 4 tokens in general. Three for each word and one `__CLS__` token that represents the entire utterance. @mkaze would you agree?

**Comment by mkaze** [comment]
Yeah, that's also an option to consider. Although we use brackets to mean contextualized embeddings; currently, only Hugging Face models (and spaCy transformers which is basically based on them) provide these kind of embeddings, and the rest only provide context-free embeddings. But that could be delegated to the user to interpret it correctly depending on the language class they are using.

**Comment by koaning** [comment]
I think we need to expect some form of maturity from the user here, yes. This is a relatively advanced feature. What I like about this is that we can keep the datastructures very similar and that should ease the congnitive load a lot.

**Comment by mkaze** [comment]
> @mkaze got any other downsides to this approach that you can think of?

Well, nothing comes to my mind for the moment.

**Comment by koaning** [comment]
Would you agree then that for now we might consider this to be the API for this use case? 

```python
lang = SpacyLanguage("bert", all_tokens=True)
lang["i like food"] 
```

This would give:

```
Embset(
    Emb["[i] like food"],
    Emb["i [like] food"],
    Emb["i like [food]"],
    Emb["[i like food]"],
)
```

It's not 100% set in stone but if we both enjoy this idea then we can start thinking about edge cases some more.

**Comment by koaning** [comment]
Since the repository moved to my personal account I'm moving this project into maintenance mode. This issue, while interesting, likely won't get the attention it needs in the future.
